
name: Automated SEO-Safe City Pages Deployment

on:
  schedule:
    # Deploy new city every 9-10 days (SEO-safe interval)
    - cron: '0 10 */9 * *'  # Every 9 days at 10 AM UTC
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deploy next city in queue'
        required: false
        default: 'false'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-next-city:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get next city in queue
        id: next-city
        run: |
          node scripts/get-next-city.js

      - name: Generate city page
        run: |
          node scripts/generate-city-page.js ${{ steps.next-city.outputs.city }}

      - name: Update deployment queue
        run: |
          node scripts/update-deployment-queue.js ${{ steps.next-city.outputs.city }}

      - name: Build site
        run: npm run build

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🚀 Deploy ${{ steps.next-city.outputs.city }} process server page - SEO automation"
          git push

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: just-legal-solutions
          directory: out

      - name: Send deployment notification
        run: |
          echo "✅ Successfully deployed ${{ steps.next-city.outputs.city }} process server page"
