name: Dynamic Content Feed Generation
on:
  push:
    paths:
      - 'content/**'
  workflow_dispatch:
jobs:
  generate-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate XML and JSON feeds
        run: |
          node scripts/generate-feeds.js
      - name: Commit and push feeds
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/feed.xml public/feed.json
          git commit -m "Auto-generate dynamic content feeds"
          git push
